[package]
name = "inboxbot"
version = "0.1.1"
edition = "2021"
description = "A telegram bot to record what you write to a file"
license = "MIT"

[[bin]]
name = "inboxbot"
path = "main.rs"

[dependencies]
teloxide = { version = "0.12", features = ["macros"] }
log = "0.4"
pretty_env_logger = "0.5"
tokio = { version = "1.36", features = ["rt-multi-thread", "macros"] }
glob = "0.3"
chrono = "0.4"
lazy_static = "1.4"
rand = "0.8"
